language: python
cache: pip
python:
  - 3.8.5
env:
  PYGLET_SHADOW_WINDOW: 'False'
  PYGLET_DEBUG_GL: 'False'
  PYGLET_AUDIO: 'silent'
addons:
  apt:
    packages:
    - freeglut3-dev
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run -m unittest
after_success:
  - codecov
